export enum RPC_ERROR {
  SERVER_NOT_STARTED = 'RPC_SERVER_NOT_STARTED',
  SERVER_NOT_FOUND = 'RPC_SERVER_NOT_FOUND',
  SERVER_CLOSED = 'RPC_SERVER_CLOSED',
  SERVICE_NOT_FOUND = 'RPC_SERVICE_NOT_FOUND',
  FAIL_CONNECT_SERVER = 'RPC_FAIL_CONNECT_SERVER',
  FAIL_SEND_MESSAGE = 'RPC_FAIL_SEND_MESSAGE',
}

export const RPC_DEFAULT_ROOT_PATH = '/regax-rpc'
